### PR TITLE
Demo

### PR DESCRIPTION
**Pull request by luisarizmendi**

### CODE REVIEW

**Comment by claudiol** [comment]
Thank you for the PR @luisarizmendi .  I will merge this once we go review the other PRs that are in flight.  If you have any questions about the Industrial Edge validated pattern please feel free to reach out to our forum-validated-patterns slack channel or our gchat space.

**Comment by mbaldessari** [comment]
This is spelled out in https://hybrid-cloud-patterns.io/industrial-edge/factory/ so at the very least we'd need a change in the docs too. Is there a specific rationale for this change?

**Comment by beekhof** [comment]
are matchLabels and matchExpressions mutually exclusive?

**Comment by mbaldessari** [comment]
> are matchLabels and matchExpressions mutually exclusive?
``
        "clusterSelector": {
          "description": "A label selector is a label query over a set of resources. The result of matchLabels and matchExpressions are ANDed. An empty label selector matches all objects. A null label selector matches no objects.",
          "type": [
            "object",
            "null"
          ],
```
Schema says they are ANDed

**Comment by mbaldessari** [comment]
I am closing this for the time being. Let me know if you want to reopen/rediscuss

**Pull request closed without merging**
