### PR TITLE
updated kfdef repo references for ODH 1.1.1

### PR DESCRIPTION
**Pull request by mamurak**
Fix for #54.

### CODE REVIEW

**Comment by claudiol** [comment]
@mamurak I will be looking into this today.  It is a reasonable request so I will test it real quick and get back to you.  Thank you for the PR!

**Comment by DanielFroehlich** [comment]
Please check! I used the RHPDS deployed version today, and the JupyterPods are still not running,

**Comment by claudiol** [comment]
Change has been tested and it works.  Merging it in.  Thank you @mamurak ! @DanielFroehlich let me know if Jupyter continues to have issues.

**Comment by DanielFroehlich** [comment]
I plan to do a recording of the ml demo tomorrow, I will let you know if it
does not work out ;-)

Daniel Fröhlich - Principal Solution Architect Industry 4.0

***@***.***  +49 176 10 24 84 33

Calendar Availability
<https://calendar.google.com/calendar/embed?src=dfroehli%40redhat.com&ctz=Europe%2FBerlin&mode=week>
TZ: CET / CST-7 / IST-4.5 / UTC+1 / EST+6 / PST+9

Red Hat GmbH <https://de.redhat.com/>, Commercial register: Amtsgericht
München, HRB 153243, Managing Directors: Charles Cachera, Brian Klemm,
Laurie Krebs, Michael O'Neill

**Pull request merged**
